name: ticker-bot
workers:
- name: ticker-bot
  environment_slug: python
  source:
    type: github
    repo: Nicolas-Oliver/ticker-bot
    branch: main
  build_command: pip install -r requirements.txt
  run_command: python main.py
  envs:
  - key: DISCORD_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: ${DISCORD_TOKEN}
  - key: MANAGEMENT_CHANNEL
    scope: RUN_AND_BUILD_TIME
    value: ${MANAGEMENT_CHANNEL}
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: INFO
